# --- DATASOURCE  ---
spring.datasource.url=jdbc:postgresql://localhost:5433/shareit
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driverClassName=org.postgresql.Driver

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ? FORCE DIALECT: Bypasses the need to query DB metadata on startup
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- HIKARI CP  ---
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# --- INIT  ---
spring.sql.init.mode=never

logging.level.ru.practicum.shareit=DEBUG
spring.jackson.serialization.fail-on-empty-beans=false